### ISSUE TITLE
Adopt helm charts

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/contrib#12]
**Motivation**

Following the discussion on the call today. There was talk of moving the existing helm chart to the `contrib` status in The Falco Project.

We need a few things to make this happen.

 - We should revist the `OWNERS` file and append with someone who can maintain and support the helm chart
 - We should compose the helm chart in such a way that we can have multiple charts for various use cases.
 - We should warn and be very clear about which charts use known attack vectors in Kubernetes (privileged=true)

```
.
├── falco-bpf-gke
│   └── helm.yaml
├── falco-grpc
│   └── helm.yaml
├── falco-module
│   ├── helm.yaml
│   └── PRIVILIGED-WARNING.txt
├── falco-operator
├── falco-prometheus-full
│   └── helm.yaml
└── falco-systemd
    └── helm.yaml
```

**Feature**

**Alternatives**

**Additional context**

**Comment by nibalizer** [comment]
Question on this: How do we manage sub-owners files. I notice in the helm/charts repo they have an `OWNERS` per directory. Is this a configuration in prow/poiana?

**Comment by kris-nova** [comment]
See https://github.com/falcosecurity/contrib/issues/13#issuecomment-624774787 for detail around `contrib` vs `repository`.

Where does the helm chart work belong?

**Comment by nibalizer** [comment]
The helm chart has more to it than documentation, so I'd expect it to be a repository. It also has a concept of releases and semver.  From the docs: "This is done as needed, and can best be measured by the need to cut a release and use the GitHub release feature" I think we easily clear that bar for helm charts.

**Comment by nibalizer** [comment]
A practical wrinkle is that the expectation is that we'll set up a helm repository, which is practically a git repo with a bunch of helm charts inside it. So we might want to create `falcosecurity/helm-charts` containing the main falco charts, the falcosidekick chart, and charts-per-usecase (see original description)

**Comment by maxgio92** [comment]
I agree with @nibalizer.

One more thing to consider I think is that at the same time, all the Kubernetes code could be in the same repository. Different projects do this, with charts definitions under _/charts_ and bare manifests under _/deploy_ (for [example](https://github.com/banzaicloud/bank-vaults)).
Anyway, for now I think that the bare manifests are not ready, so they should remain in the contrib.

**Comment by leodido** [comment]
@nibalizer @poiana understands nested OWNERS file (also it's able to merge them or not, depending on how we want it to behave, that bad bird!)

**Comment by leodido** [comment]
Regarding the _status_ of the helm(s) chart(s) into the falcosecurity organization.

As long we have a list of OWNERS that take responsibility on maintaining them, I'm ok promoting them to _repository_ status from the _sandbox_ one (ie., this repo).

**Comment by nibalizer** [comment]
I'll sign up for maintenance.

**Comment by leodido** [comment]
@bencer sign ups for maintenance as a reviewer

what about @nestorsalceda ?

**Comment by nestorsalceda** [comment]
Hey @leodido 

I have been thinking a lot about this decision these past days and I think that right now I don't have enough time to support the chart with the quality that I would like. So I think that is better to step down and don't make promises that I can't keep.

I really enjoyed the time I spent working on the Falco Helm Chart trying to make Falco more accessible to the potential users. And of course, if someone has some questions, I will be glad to answer them :)

Thanks for the ping!

**Comment by nibalizer** [comment]
Thanks for the good work @nestorsalceda :)

**Comment by maxgio92** [comment]
Thanks @nestorsalceda!

**Comment by kris-nova** [comment]
Thanks for all your hard work @nestorsalceda! 

We have preserved your original work and the community will always be here if you want to come back and say hello. 

---

The Falco helm charts repository has been created [github.com/falsosecurity/charts](https://github.com/falcosecurity/charts).

Welcome to the Falco project
